@echo off
echo Starting Travel Website...
echo.
echo Step 1: Installing dependencies...
call npm install
echo.
echo Step 2: Building the React application...
call npm run build
echo.
echo Step 3: Starting the server on port 8080...
call npm run server